name: Docker Image CI/CD and Deployment AWS Elastic Beanstalk
on: [push]

env:
  EB_PACKAGE_S3_BUCKET_NAME : "helloworld.flask-app"
  EB_APPLICATION_NAME       : "Helloworld"
  EB_ENVIRONMENT_NAME       : "Helloworld-env"
  DEPLOY_PACKAGE_NAME       : "Helloworld-app-${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-west-2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/helloworld:latest
      
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Image push
      run: docker push ${{ secrets.DOCKER_USER }}/helloworld:latest 
      
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Generate deployment package
      run: zip deploy.zip *.js *.json *.html *.css
         
    - name: Git clone our repository
      uses: actions/checkout@v1
            
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./  -x  *.git*
           
    - name: Configure my AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
           aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
           aws-region           : ${{ env.AWS_REGION_NAME }}

    - name: Copy our Deployment package to S3 bucket
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/
      
    - name: Create new ElasticBeanstalk Application Version
      run : |
            aws elasticbeanstalk create-application-version \
            --application-name ${{ env.EB_APPLICATION_NAME }} \
            --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
            --version-label "Ver-${{ github.sha }}" \
            --description "CommitSHA-${{ github.sha }}"
         
    - name: Deploy our new Application Version
      run : aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Ver-${{ github.sha }}"
