name: Docker Image CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
#     - name: Set Tag in evn variable
#       run: echo ${TAG}
#       env:
#         TAG: 3.1
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/helloworld:latest
      
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Image push
      run: docker push ${{ secrets.DOCKER_USER }}/helloworld:latest
